name: moewe
description: a client library for m≈ìwe
version: 0.1.3
repository: https://github.com/RobinNaumann/moewe_dart

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
